name: Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged

    steps:
      - name: Tag
        id: tag-action
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test output
        if: (steps.tag-action.outputs.tag != '')
        run: echo karaba1 karaba2 ${{ steps.tag-action.outputs.tag }} karaba
